In [2]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv('Dataset- Telecom-1.xlsx - telecom_data_python.csv')
df.head()

SUBS_KEY  TARGET  OG_MOU_F4  IC_MOU_F4  OG_CALLS_F4  IC_CALLS_F4  \
0  623576580       1       2.93       0.00            1            0   
1  623576616       0      23.03      59.03            6           14   
2  623576617       0      16.25      24.73           12           18   
3  623576618       1       3.27       6.42            4           10   
4  623576655       1       0.00       0.00            0            0   

   RCHG_AMOUNT_F4  CNT_RCHG_F4  AVG_MBL_F4  IC_OG_RATIO_F4  ...  \
0               0            0        9.12            0.00  ...   
1               0            0        1.33            2.56  ...   
2              95            2       16.48            1.52  ...   
3               0            0        7.70            1.96  ...   
4               0            0       10.00          999.00  ...   

   AVG_NIG_USG_F10  AVG_STD_USG_F4  AVG_STD_USG_F7  AVG_STD_USG_F10  DND  \
0             0.00            0.00            0.00             0.00    0   
1             0.00            1.88            0.51             0.58    0   
2             0.14            0.00            0.00             0.00    0   
3             0.17            0.00            0.00             0.00    0   
4             0.00            0.00            0.00             0.00    0   

   DND_INFO  CHG_IC_MOU_L5_F5  USAGE_SPREAD  SUM_RCHG_MRP_L10  TARGET_21_30  
0         0              0.00          0.04                 0             1  
1         0             -0.25          0.30                70             0  
2         0              0.77          0.36               288             0  
3         0              0.11          0.26                 0             1  
4         0              0.00          0.00                 0             0  

[5 rows x 109 columns]

In [5]:
df.columns

Index(['SUBS_KEY', 'TARGET', 'OG_MOU_F4', 'IC_MOU_F4', 'OG_CALLS_F4',
       'IC_CALLS_F4', 'RCHG_AMOUNT_F4', 'CNT_RCHG_F4', 'AVG_MBL_F4',
       'IC_OG_RATIO_F4',
       ...
       'AVG_NIG_USG_F10', 'AVG_STD_USG_F4', 'AVG_STD_USG_F7',
       'AVG_STD_USG_F10', 'DND', 'DND_INFO', 'CHG_IC_MOU_L5_F5',
       'USAGE_SPREAD', 'SUM_RCHG_MRP_L10', 'TARGET_21_30'],
      dtype='object', length=109)

In [6]:
metadata=pd.read_csv('Metadata_telecom.csv')
metadata

Variable                                        Description
0       ACTIVATION_DT       Day in the month on which activation is done
1         AVG_MBL_F10  Average main balance in first 10 days from act...
2          AVG_MBL_F4  Average main balance in first 4 days from acti...
3          AVG_MBL_F7  Average main balance in first 7 days from acti...
4     AVG_NIG_USG_F10  Average night usage in first 10 days from acti...
..                ...                                                ...
104          SUBS_KEY                                  Unique Identifier
105  SUM_RCHG_MRP_L10            Sum of recharge amount in first 10 days
106            TARGET                                Churn in next month
107      TARGET_21_30                     Churn in between 21 to 30 days
108      USAGE_SPREAD        Score on the uniform usage in first 10 days

[109 rows x 2 columns]

In [7]:
metadata[1:11]

Variable                                        Description
1        AVG_MBL_F10  Average main balance in first 10 days from act...
2         AVG_MBL_F4  Average main balance in first 4 days from acti...
3         AVG_MBL_F7  Average main balance in first 7 days from acti...
4    AVG_NIG_USG_F10  Average night usage in first 10 days from acti...
5     AVG_NIG_USG_F4  Average night usage in first 4 days from activ...
6     AVG_NIG_USG_F7  Average night usage in first 7 days from activ...
7    AVG_STD_USG_F10  Average STD usage in first 10 days from activa...
8     AVG_STD_USG_F4  Average STD usage in first 4 days from activation
9     AVG_STD_USG_F7  Average STD usage in first 7 days from activation
10  CHG_IC_MOU_L5_F5  Percentage change in incoming minute of usage ...

In [8]:
metadata[11:21]

Variable                                        Description
11   CNT_DEC_INS_F10  Count of days where balance is deducted in fir...
12    CNT_DEC_INS_F4  Count of days where balance is deducted in fir...
13    CNT_DEC_INS_F7  Count of days where balance is deducted in fir...
14      CNT_RCHG_F10                 Count of recharge in first 10 days
15       CNT_RCHG_F4                  Count of recharge in first 4 days
16       CNT_RCHG_F7                  Count of recharge in first 7 days
17  CNT_ROAM_INS_F10  Count of days customer is in roaming zone in f...
18   CNT_ROAM_INS_F4  Count of days customer is in roaming zone in f...
19   CNT_ROAM_INS_F7  Count of days customer is in roaming zone in f...
20   CNT_SMS_INS_F10             Count of SMS instance in first 10 days

In [9]:
metadata[21:31]

Variable                                      Description
21      CNT_SMS_INS_F4            Count of SMS instance in first 4 days
22      CNT_SMS_INS_F7            Count of SMS instance in first 7 days
23  CNT_STD_IC_INS_F10  Count of incoming STD instance in first 10 days
24   CNT_STD_IC_INS_F4   Count of incoming STD instance in first 4 days
25   CNT_STD_IC_INS_F7   Count of incoming STD instance in first 7 days
26     CNT_STD_INS_F10           Count of STD instance in first 10 days
27      CNT_STD_INS_F4            Count of STD instance in first 4 days
28      CNT_STD_INS_F7            Count of STD instance in first 7 days
29  CNT_STD_OG_INS_F10  Count of outgoing STD instance in first 10 days
30   CNT_STD_OG_INS_F4   Count of outgoing STD instance in first 4 days

In [10]:
metadata[31:41]

Variable                                        Description
31  CNT_STD_OG_INS_F7     Count of outgoing STD instance in first 7 days
32    CNT_VLR_INS_F10  Count of days customer is latching on network ...
33     CNT_VLR_INS_F4  Count of days customer is latching on network ...
34     CNT_VLR_INS_F7  Count of days customer is latching on network ...
35    DAY_END_MBL_F10                     End of day balance on 10th day
36     DAY_END_MBL_F4                          End of balance on 4th day
37     DAY_END_MBL_F7                          End of balance on 7th day
38                DND           Promotional call received inspite of DND
39           DND_INFO                                Do not disturb flag
40    DS_IC_CALLS_F10      Day since incoming call come in first 10 days

In [11]:
metadata[41:51]

Variable                                        Description
41   DS_IC_CALLS_F4       Day since incoming call come in first 4 days
42   DS_IC_CALLS_F7       Day since incoming call come in first 7 days
43    DS_IC_MOU_F10  Day since incoming minute of usage come in fir...
44     DS_IC_MOU_F4  Day since incoming minute of usage come in fir...
45     DS_IC_MOU_F7  Day since incoming minute of usage come in fir...
46  DS_OG_CALLS_F10      Day since outgoing call done in first 10 days
47   DS_OG_CALLS_F4       Day since outgoing call done in first 4 days
48   DS_OG_CALLS_F7       Day since outgoing call done in first 7 days
49    DS_OG_MOU_F10  Day since outgoing minute of usage come in fir...
50     DS_OG_MOU_F4  Day since outgoing minute of usage come in fir...

In [12]:
metadata[51:61]

Variable                                        Description
51         DS_OG_MOU_F7  Day since outgoing minute of usage come in fir...
52      DS_RCHG_MRP_F10                Day since recharge in first 10 days
53  DS_RCHG_MRP_F10_EX1  Day since recharge in first 10 days excluding ...
54       DS_RCHG_MRP_F4                 Day since recharge in first 4 days
55   DS_RCHG_MRP_F4_EX1  Day since recharge in first 4 days excluding 1...
56       DS_RCHG_MRP_F7                 Day since recharge in first 7 days
57   DS_RCHG_MRP_F7_EX1  Day since recharge in first 7 days excluding 1...
58         IC_CALLS_F10                    Incoming calls in first 10 days
59          IC_CALLS_F4                     Incoming calls in first 4 days
60          IC_CALLS_F7                     Incoming calls in first 7 days

In [13]:
metadata[61:71]

Variable                                        Description
61       IC_MOU_F10          Incoming minute of usage in first 10 days
62        IC_MOU_F4           Incoming minute of usage in first 4 days
63        IC_MOU_F7           Incoming minute of usage in first 7 days
64  IC_OG_RATIO_F10       Incoming to Outgoing ration in first 10 days
65   IC_OG_RATIO_F4        Incoming to Outgoing ration in first 4 days
66   IC_OG_RATIO_F7        Incoming to Outgoing ration in first 7 days
67      MAX_MBL_F10                  Max main balance in first 10 days
68  MAX_MBL_F10_EX1  Max main balance in first 10 days excluding 1s...
69       MAX_MBL_F4                   Max main balance in first 4 days
70   MAX_MBL_F4_EX1  Max main balance in first 4 days excluding 1st...

In [14]:
metadata[71:81]

Variable                                        Description
71            MAX_MBL_F7                   Max main balance in first 7 days
72        MAX_MBL_F7_EX1  Max main balance in first 7 days excluding 1st...
73  MAX_MRP_HIGH_AMT_F10            Max amount of recharge in first 10 days
74   MAX_MRP_HIGH_AMT_F4             Max amount of recharge in first 4 days
75   MAX_MRP_HIGH_AMT_F7             Max amount of recharge in first 7 days
76          OG_CALLS_F10                    Outgoing calls in first 10 days
77           OG_CALLS_F4                     Outgoing calls in first 4 days
78           OG_CALLS_F7                     Outgoing calls in first 7 days
79            OG_MOU_F10          Outgoing minute of usage in first 10 days
80             OG_MOU_F4           Outgoing minute of usage in first 4 days

In [15]:
metadata[81:91]

Variable                                        Description
81        OG_MOU_F7           Outgoing minute of usage in first 7 days
82  RCHG_AMOUNT_F10             Total recharge amount in first 10 days
83   RCHG_AMOUNT_F4              Total recharge amount in first 4 days
84   RCHG_AMOUNT_F7              Total recharge amount in first 7 days
85     SD_ICMOU_F10  Standard deviation of incoming minute of usage...
86      SD_ICMOU_F4  Standard deviation of incoming minute of usage...
87      SD_ICMOU_F7  Standard deviation of incoming minute of usage...
88       SD_MBL_F10  Standard deviation of main balance in first 10...
89        SD_MBL_F4  Standard deviation of main balance in first 4 ...
90        SD_MBL_F7  Standard deviation of main balance in first 7 ...

In [16]:
metadata[91:]

Variable                                        Description
91         SD_OGMOU_F10  Standard deviation of outgoing minute of usage...
92          SD_OGMOU_F4  Standard deviation of outgoing minute of usage...
93          SD_OGMOU_F7  Standard deviation of outgoing minute of usage...
94        SLP_ICMOU_F10  Slope of incoming minute of usage in first 10 ...
95         SLP_ICMOU_F4  Slope of incoming minute of usage in first 4 days
96         SLP_ICMOU_F7  Slope of incoming minute of usage in first 7 days
97          SLP_MBL_F10             Slope of main balance in first 10 days
98           SLP_MBL_F4              Slope of main balance in first 4 days
99           SLP_MBL_F7               Slope of main balance in first 7days
100       SLP_OGMOU_F10  Slope of outgoing minute of usage in first 10 ...
101        SLP_OGMOU_F4  Slope of outgoing minute of usage in first 4 days
102        SLP_OGMOU_F7  Slope of outgoing minute of usage in first 7 days
103  SUBS_ACTIVATION_DT                                 Date of Activation
104            SUBS_KEY                                  Unique Identifier
105    SUM_RCHG_MRP_L10            Sum of recharge amount in first 10 days
106              TARGET                                Churn in next month
107        TARGET_21_30                     Churn in between 21 to 30 days
108        USAGE_SPREAD        Score on the uniform usage in first 10 days

In [17]:
df

SUBS_KEY  TARGET  OG_MOU_F4  IC_MOU_F4  OG_CALLS_F4  IC_CALLS_F4  \
0     623576580       1       2.93       0.00            1            0   
1     623576616       0      23.03      59.03            6           14   
2     623576617       0      16.25      24.73           12           18   
3     623576618       1       3.27       6.42            4           10   
4     623576655       1       0.00       0.00            0            0   
...         ...     ...        ...        ...          ...          ...   
4995  623614881       1       0.00       0.97            1            3   
4996  623614882       0       3.63       9.70            6            9   
4997  623614883       1       0.00       0.00            0            0   
4998  623614884       0      11.02       1.97            8            2   
4999  623614885       1       0.00       0.37            0            1   

      RCHG_AMOUNT_F4  CNT_RCHG_F4  AVG_MBL_F4  IC_OG_RATIO_F4  ...  \
0                  0            0        9.12            0.00  ...   
1                  0            0        1.33            2.56  ...   
2                 95            2       16.48            1.52  ...   
3                  0            0        7.70            1.96  ...   
4                  0            0       10.00          999.00  ...   
...              ...          ...         ...             ...  ...   
4995              58            1       67.40          999.00  ...   
4996               0            0        6.85            2.67  ...   
4997             198            1       10.00          999.00  ...   
4998              48            1       55.00            0.18  ...   
4999              18            1       22.33          999.00  ...   

      AVG_NIG_USG_F10  AVG_STD_USG_F4  AVG_STD_USG_F7  AVG_STD_USG_F10  DND  \
0                0.00            0.00            0.00             0.00    0   
1                0.00            1.88            0.51             0.58    0   
2                0.14            0.00            0.00             0.00    0   
3                0.17            0.00            0.00             0.00    0   
4                0.00            0.00            0.00             0.00    0   
...               ...             ...             ...              ...  ...   
4995             0.00            0.00            0.00             0.00    0   
4996             0.00            0.00            0.00             0.00    0   
4997             0.00            0.00            0.00             0.00    0   
4998             0.00            0.24            0.14             0.08    0   
4999             0.00            0.00            0.00             0.00    0   

      DND_INFO  CHG_IC_MOU_L5_F5  USAGE_SPREAD  SUM_RCHG_MRP_L10  TARGET_21_30  
0            0              0.00          0.04                 0             1  
1            0             -0.25          0.30                70             0  
2            0              0.77          0.36               288             0  
3            0              0.11          0.26                 0             1  
4            0              0.00          0.00                 0             0  
...        ...               ...           ...               ...           ...  
4995         0             -0.52          0.08                58             1  
4996         0              1.21          0.18                20             0  
4997         0              0.00          0.04               198             0  
4998         0             -1.00          0.18                48             0  
4999         0             -1.00          0.08                49             1  

[5000 rows x 109 columns]

In [18]:
df['RCHG_AMOUNT_F7']

0         0
1        70
2       288
3         0
4         0
       ... 
4995     58
4996      0
4997    198
4998     48
4999     49
Name: RCHG_AMOUNT_F7, Length: 5000, dtype: int64

In [19]:
df[df['MAX_MRP_HIGH_AMT_F7']==df['MAX_MRP_HIGH_AMT_F7'].max()]

SUBS_KEY  TARGET  OG_MOU_F4  IC_MOU_F4  OG_CALLS_F4  IC_CALLS_F4  \
33  623576823       1       0.98       0.83            1            1   

    RCHG_AMOUNT_F4  CNT_RCHG_F4  AVG_MBL_F4  IC_OG_RATIO_F4  ...  \
33            1920            3      227.56            0.85  ...   

    AVG_NIG_USG_F10  AVG_STD_USG_F4  AVG_STD_USG_F7  AVG_STD_USG_F10  DND  \
33              0.0             0.0             0.0              0.0    0   

    DND_INFO  CHG_IC_MOU_L5_F5  USAGE_SPREAD  SUM_RCHG_MRP_L10  TARGET_21_30  
33         0              -1.0          0.04              1920             0  

[1 rows x 109 columns]

In [20]:
df[df['MAX_MRP_HIGH_AMT_F7']==df['MAX_MRP_HIGH_AMT_F7'].max()][['MAX_MRP_HIGH_AMT_F7','CNT_VLR_INS_F10']]

MAX_MRP_HIGH_AMT_F7  CNT_VLR_INS_F10
33                 1495               10

# 1. The sales manager wants to know about a customer who has the highest recharge in the first 7 days and how many days that customer is on VLR (being on the network) in the first 10 days?

In [21]:
df[df['MAX_MRP_HIGH_AMT_F7']==df['MAX_MRP_HIGH_AMT_F7'].max()]

SUBS_KEY  TARGET  OG_MOU_F4  IC_MOU_F4  OG_CALLS_F4  IC_CALLS_F4  \
33  623576823       1       0.98       0.83            1            1   

    RCHG_AMOUNT_F4  CNT_RCHG_F4  AVG_MBL_F4  IC_OG_RATIO_F4  ...  \
33            1920            3      227.56            0.85  ...   

    AVG_NIG_USG_F10  AVG_STD_USG_F4  AVG_STD_USG_F7  AVG_STD_USG_F10  DND  \
33              0.0             0.0             0.0              0.0    0   

    DND_INFO  CHG_IC_MOU_L5_F5  USAGE_SPREAD  SUM_RCHG_MRP_L10  TARGET_21_30  
33         0              -1.0          0.04              1920             0  

[1 rows x 109 columns]

# 2. The marketing manager wants to know the average SLP IC MOU (slope ofIncoming call minute of usage) in the first 7 days of churned customers between 21to 30 days, so he can plan a marketing campaign accordingly.


In [22]:
df['TARGET_21_30'].unique()

array([1, 0], dtype=int64)

In [49]:
df[df['TARGET_21_30']==1]['SLP_ICMOU_F7'].mean()

0.18823757763975155

#3. Management is planning to launch an offer where they are offering the first 7 daysof free calling services. So, they must identify the customer who has churnedbetween 21 to 30 days and has not made any OG (outgoing) and IC (incoming call)calls in the first seven days. How many such customers are present in the data?

In [51]:
df['DS_IC_CALLS_F7'].unique()

array([19,  0,  1,  5,  2,  3,  4,  6])

In [52]:
df['DS_OG_CALLS_F7'].unique()

array([ 3,  0,  2, 19,  5,  1,  6,  4])

In [53]:
df[(df['TARGET_21_30']==0)&(df['DS_IC_CALLS_F7']==0)&(df['DS_OG_CALLS_F7']==0)].shape[0]

759

# 4. In telecom, DND customers are more stable as compared to non-DND customers.Management is more concerned about the churn of DND customers after a month.What is the churn rate of the DND customer?


In [54]:
df['DND_INFO'].unique()

array([0, 1])

In [55]:
df['DND'].unique()

array([  0,  29,  61,  58, 203,  90,  87, 174])

In [62]:
metadata[metadata['Variable']=='DND']

Variable                               Description
38      DND  Promotional call received inspite of DND

In [64]:
metadata[metadata['Variable']=='DND_INFO']

Variable          Description
39  DND_INFO  Do not disturb flag

In [70]:
df[df['DND_INFO']==1]['TARGET_21_30'].unique()

array([0, 1])

In [71]:
df[df['DND_INFO']==1]['TARGET'].unique()

array([1, 0])

#5. The product manager wants to know the best-selling recharge. Which is the most common total recharge amount in the first 10 days?


In [75]:
df['MAX_MRP_HIGH_AMT_F10']

0         0
1        70
2       123
3         0
4         0
       ... 
4995     58
4996     20
4997    198
4998     48
4999     31
Name: MAX_MRP_HIGH_AMT_F10, Length: 5000, dtype: int64

In [79]:
chg_10=df['RCHG_AMOUNT_F10']

In [80]:
chg_10

0         0
1        70
2       288
3         0
4         0
       ... 
4995     58
4996     20
4997    198
4998     48
4999     49
Name: RCHG_AMOUNT_F10, Length: 5000, dtype: int64

#6. The product manager wants to know how many customers have used the balance in the first 10 days. (HINT: They have constant balance in the first 4 and 10 days)


In [85]:
metadata[metadata['Variable']=='MAX_MBL_F10']

Variable                        Description
67  MAX_MBL_F10  Max main balance in first 10 days

In [86]:
metadata[metadata['Variable']=='MAX_MBL_F4']

Variable                       Description
69  MAX_MBL_F4  Max main balance in first 4 days

In [90]:
df1=df[df['MAX_MBL_F4']==df['MAX_MBL_F10']]

In [91]:
df1.shape[0]

4440

# 1. Create a 3D NumPy array having the values mentioned below in picture.

In [23]:
arr1=np.array([10,0,10]*3).reshape(3,3)

In [24]:
arr1

array([[10,  0, 10],
       [10,  0, 10],
       [10,  0, 10]])

In [25]:
arr2=np.zeros((3,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.fill_diagonal(arr2,[10,0,10])

In [27]:
np.fill_diagonal(np.fliplr(arr2),[10,0,10])

In [28]:
arr2

array([[10.,  0., 10.],
       [ 0.,  0.,  0.],
       [10.,  0., 10.]])

In [29]:
arr1

array([[10,  0, 10],
       [10,  0, 10],
       [10,  0, 10]])

In [30]:
arr2

array([[10.,  0., 10.],
       [ 0.,  0.,  0.],
       [10.,  0., 10.]])

In [37]:
np.concatenate((arr1,arr2,arr1),axis=0).reshape(3,3,3)

array([[[10.,  0., 10.],
        [10.,  0., 10.],
        [10.,  0., 10.]],

       [[10.,  0., 10.],
        [ 0.,  0.,  0.],
        [10.,  0., 10.]],

       [[10.,  0., 10.],
        [10.,  0., 10.],
        [10.,  0., 10.]]])